CREATE TABLE IF NOT EXISTS d_customer (
    c_customer_sk int,
    c_customer_id String,
    c_first_shipto_date_sk int,
    c_first_sales_date_sk int,
    c_salutation String,
    c_first_name String,
    c_last_name String,
    c_preferred_cust_flag String,
    c_birth_day int,
    c_birth_month int,
    c_birth_year int,
    c_birth_country String,
    c_login String,
    c_email_address String,
    c_last_review_date int
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_date_dim (
    d_date_sk int,
    d_date_id String,
    d_date Date,
    d_month_seq int,
    d_week_seq int,
    d_quarter_seq int,
    d_year int,
    d_dow int,
    d_moy int,
    d_dom int,
    d_qoy int,
    d_fy_year int,
    d_fy_quarter_seq int,
    d_fy_week_seq int,
    d_day_name String,
    d_quarter_name String,
    d_holiday String,
    d_weekend String,
    d_following_holiday String,
    d_first_dom int,
    d_last_dom int,
    d_same_day_ly int,
    d_same_day_lq int,
    d_current_day String,
    d_current_week String,
    d_current_month String,
    d_current_quarter String,
    d_current_year String
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_item (
    i_category String,
    i_item_sk int,
    i_item_id String,
    i_rec_start_date Date,
    i_rec_end_date Date,
    i_item_desc String,
    i_current_price Decimal,
    i_wholesale_cost Decimal,
    i_brand_id int,
    i_brand String,
    i_class_id int,
    i_class String,
    i_category_id int,
    i_manufact_id int,
    i_manufact String,
    i_size String,
    i_formulation String,
    i_color String,
    i_units String,
    i_container String,
    i_manager_id int,
    i_product_name String,
    i_category_sk BigInt
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_store (
    s_country String,
    s_city String,
    s_store_sk int,
    s_store_id String,
    s_rec_start_date Date,
    s_rec_end_date Date,
    s_closed_date_sk int,
    s_store_name String,
    s_number_employees int,
    s_floor_space int,
    s_hours String,
    s_manager String,
    s_market_id int,
    s_geography_class String,
    s_market_desc String,
    s_market_manager String,
    s_division_id int,
    s_division_name String,
    s_company_id int,
    s_company_name String,
    s_street_number String,
    s_street_name String,
    s_street_type String,
    s_suite_number String,
    s_county String,
    s_state String,
    s_zip String,
    s_gmt_offset Decimal,
    s_tax_percentage Decimal,
    s_city_sk BigInt,
    s_country_sk BigInt
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_item_category (
    ic_category String,
    ic_category_sk BigInt
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_store_city (
    sc_city String,
    sc_city_sk BigInt)
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS d_store_country (
    sc_country String,
    sc_country_sk BigInt
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS f_store_sales (
    ss_store_sk int,
    ss_item_sk int,
    ss_sold_date_sk int,
    ss_customer_sk int,
    ss_ticket_number int,
    ss_quantity int,
    ss_wholesale_cost Decimal,
    ss_list_price Decimal,
    ss_sales_price Decimal,
    ss_ext_discount_amt Decimal,
    ss_ext_sales_price Decimal,
    ss_ext_wholesale_cost Decimal,
    ss_ext_list_price Decimal,
    ss_ext_tax Decimal,
    ss_coupon_amt Decimal,
    ss_net_paid Decimal,
    ss_net_paid_inc_tax Decimal,
    ss_net_profit Decimal,
    ss_d_date Date,
    ss_item_category_sk BigInt,
    ss_store_city_sk BigInt,
    ss_store_country_sk BigInt
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS a_store_sales_store_lvl (
    ss_d_date Date,
    ss_store_sk int,
    count_ss_item_sk BigInt,
    cnt_dist_ss_item_sk BigInt,
    cnt_dist_ss_customer_sk BigInt,
    cnt_dist_ss_ticket_number BigInt,
    sum_ss_item_sk BigInt,
    sum_ss_quantity BigInt,
    sum_ss_wholesale_cost Decimal,
    sum_ss_list_price Decimal,
    sum_ss_sales_price Decimal,
    sum_ss_ext_discount_amt Decimal,
    sum_ss_ext_list_price Decimal,
    sum_ss_ext_tax Decimal,
    sum_ss_coupon_amt Decimal,
    sum_ss_net_paid Decimal,
    sum_ss_net_paid_inc_tax Decimal,
    sum_ss_net_profit Decimal,
    avg_ss_item_sk Double,
    avg_ss_quantity Double,
    avg_ss_wholesale_cost Decimal,
    avg_ss_list_price Decimal,
    avg_ss_sales_price Decimal,
    avg_ss_ext_discount_amt Decimal,
    avg_ss_ext_list_price Decimal,
    avg_ss_ext_tax Decimal,
    avg_ss_coupon_amt Decimal,
    avg_ss_net_paid Decimal,
    avg_ss_net_paid_inc_tax Decimal,
    avg_ss_net_profit Decimal
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS a_store_sales_customer_lvl (
    ss_d_date Date,
    ss_customer_sk int,
    count_ss_item_sk BigInt,
    cnt_dist_ss_item_sk BigInt,
    cnt_dist_ss_store_sk BigInt,
    cnt_dist_ss_ticket_number BigInt,
    sum_ss_item_sk BigInt,
    sum_ss_quantity BigInt,
    sum_ss_wholesale_cost Decimal,
    sum_ss_list_price Decimal,
    sum_ss_sales_price Decimal,
    sum_ss_ext_discount_amt Decimal,
    sum_ss_ext_list_price Decimal,
    sum_ss_ext_tax Decimal,
    sum_ss_coupon_amt Decimal,
    sum_ss_net_paid Decimal,
    sum_ss_net_paid_inc_tax Decimal,
    sum_ss_net_profit Decimal,
    avg_ss_item_sk Double,
    avg_ss_quantity Double,
    avg_ss_wholesale_cost Decimal,
    avg_ss_list_price Decimal,
    avg_ss_sales_price Decimal,
    avg_ss_ext_discount_amt Decimal,
    avg_ss_ext_list_price Decimal,
    avg_ss_ext_tax Decimal,
    avg_ss_coupon_amt Decimal,
    avg_ss_net_paid Decimal,
    avg_ss_net_paid_inc_tax Decimal,
    avg_ss_net_profit Decimal
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS a_store_sales_item_lvl (
    ss_d_date Date,
    ss_item_sk int,
    count_ss_item_sk BigInt,
    cnt_dist_ss_store_sk BigInt,
    cnt_dist_ss_customer_sk BigInt,
    cnt_dist_ss_ticket_number BigInt,
    sum_ss_item_sk BigInt,
    sum_ss_quantity BigInt,
    sum_ss_wholesale_cost Decimal,
    sum_ss_list_price Decimal,
    sum_ss_sales_price Decimal,
    sum_ss_ext_discount_amt Decimal,
    sum_ss_ext_list_price Decimal,
    sum_ss_ext_tax Decimal,
    sum_ss_coupon_amt Decimal,
    sum_ss_net_paid Decimal,
    sum_ss_net_paid_inc_tax Decimal,
    sum_ss_net_profit Decimal,
    avg_ss_item_sk Double,
    avg_ss_quantity Double,
    avg_ss_wholesale_cost Decimal,
    avg_ss_list_price Decimal,
    avg_ss_sales_price Decimal,
    avg_ss_ext_discount_amt Decimal,
    avg_ss_ext_list_price Decimal,
    avg_ss_ext_tax Decimal,
    avg_ss_coupon_amt Decimal,
    avg_ss_net_paid Decimal,
    avg_ss_net_paid_inc_tax Decimal,
    avg_ss_net_profit Decimal
) STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS a_store_sales_store_quantity_ma (
    ss_d_date Date,
    ss_store_sk int,
    avg_ss_quantity Double,
    7d_ma_quantity Double,
    1m_ma_quantity Double,
    1q_ma_quantity Double
) STORED AS PARQUET;